# Generated by Django 2.0.2 on 2018-07-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_value', models.FloatField(default=0)),
                ('amount_available', models.FloatField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_moved', models.IntegerField(default=0)),
                ('current_price', models.FloatField(default=0)),
                ('time', models.DateTimeField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Account')),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
